spring:
  kafka:
    consumer:
      bootstrap-servers: localhost:9092
      group-id: group_id
      auto-offset-reset: earliest
      key-deserializer: org.apache.kafka.common.serialization.StringDeserializer
      value-deserializer: org.apache.kafka.common.serialization.StringDeserializer
    producer:
      bootstrap-servers: localhost:9092
      key-serializer: org.apache.kafka.common.serialization.StringSerializer
      value-serializer: org.apache.kafka.common.serialization.StringSerializer
    template:
      default-topic: message-topic
  jpa:
    hibernate:
      ddl-auto: update
    show-sql: true
  datasource:
    platform: POSTGRESQL
    url: jdbc:postgresql://0.0.0.0:5432/app
    password: fordemopurpose
    username: postgres
    driverClassName: org.postgresql.Driver

server:
  port: 9000